package quy.com.entity;
// Generated 29-jul-2016 17:25:51 by Hibernate Tools 4.3.4.Final

import java.util.Date;

/**
 * DetailGroup generated by hbm2java
 */
public class DetailGroup implements java.io.Serializable {

	private Integer id;
	private Group group;
	private User user;
	private Integer position;
	private Character rol;
	private Character state;
	private Date paymentDate;

	public DetailGroup() {
	}

	public DetailGroup(Group group, User user, Integer position, Character rol, Character state, Date paymentDate) {
		this.group = group;
		this.user = user;
		this.position = position;
		this.rol = rol;
		this.state = state;
		this.paymentDate = paymentDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public Character getRol() {
		return this.rol;
	}

	public void setRol(Character rol) {
		this.rol = rol;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

}
