package quy.com.entity;
// Generated 23-jul-2016 18:50:41 by Hibernate Tools 4.3.4.Final

/**
 * DetailGroup generated by hbm2java
 */
public class DetailGroup implements java.io.Serializable {

	private Integer id;
	private Group group;
	private User user;
	private Integer userOrder;

	public DetailGroup() {
	}

	public DetailGroup(Group group, User user, Integer userOrder) {
		this.group = group;
		this.user = user;
		this.userOrder = userOrder;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getUserOrder() {
		return this.userOrder;
	}

	public void setUserOrder(Integer userOrder) {
		this.userOrder = userOrder;
	}

}
