package quy.com.entity;
// Generated 23-jul-2016 18:50:41 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private Set detailGroups = new HashSet(0);

	public Group() {
	}

	public Group(String name, Set detailGroups) {
		this.name = name;
		this.detailGroups = detailGroups;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDetailGroups() {
		return this.detailGroups;
	}

	public void setDetailGroups(Set detailGroups) {
		this.detailGroups = detailGroups;
	}

}
