package quy.com.entity;
// Generated 26-jul-2016 9:58:34 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String facebookId;
	private String urlPicture;
	private Set detailGroups = new HashSet(0);
	private Set groups = new HashSet(0);

	public User() {
	}

	public User(String name, String facebookId, String urlPicture, Set detailGroups, Set groups) {
		this.name = name;
		this.facebookId = facebookId;
		this.urlPicture = urlPicture;
		this.detailGroups = detailGroups;
		this.groups = groups;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}

	public Set getDetailGroups() {
		return this.detailGroups;
	}

	public void setDetailGroups(Set detailGroups) {
		this.detailGroups = detailGroups;
	}

	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

}
