package quy.com.entity;
 
// Generated 21-jul-2016 22:15:56 by Hibernate Tools 4.3.4.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String name;
	private String facebookId;
	private String urlPicture;

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public User(int userId, String name, String facebookId, String urlPicture) {
		this.userId = userId;
		this.name = name;
		this.facebookId = facebookId;
		this.urlPicture = urlPicture;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}
}