package quy.com.entity;
// Generated 29-jul-2016 17:25:51 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String facebookId;
	private String urlPicture;
	private String email;
	private String mobile;
	private char state;
	private Set detailGroups = new HashSet(0);
	private Set groups = new HashSet(0);

	public User() {
	}

	public User(char state) {
		this.state = state;
	}

	public User(String name, String facebookId, String urlPicture, String email, String mobile, char state,
			Set detailGroups, Set groups) {
		this.name = name;
		this.facebookId = facebookId;
		this.urlPicture = urlPicture;
		this.email = email;
		this.mobile = mobile;
		this.state = state;
		this.detailGroups = detailGroups;
		this.groups = groups;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public char getState() {
		return this.state;
	}

	public void setState(char state) {
		this.state = state;
	}

	public Set getDetailGroups() {
		return this.detailGroups;
	}

	public void setDetailGroups(Set detailGroups) {
		this.detailGroups = detailGroups;
	}

	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

}
